### ISSUE TITLE
localization path-parsing regex in generated gulpfile.localization fails on unix systems

### ISSUE THREAD

**Issue by ddamico-cbc** [Allov/generator-koco#5]
Probably a low-priority issue since I think the total number of *nix users on the team is 1, but I'm running into an issue with the component-name-seeking in the generated gulpfile.localization file, as the regex used in getComponentNameFromPath is assuming a windows-formatted path, as far as slashes.

For the time being, here's the alternative implementation I've patched in locally to get things going...

``` javascript
function getComponentNameFromPath(incomingPath, lng) {

   var splitPath = incomingPath.split(path.sep);
   var suspectedComponentName = splitPath[splitPath.indexOf('localization') - 1];
   return (suspectedComponentName != '') ? suspectedComponentName : null;

}
```

Probably lots of room for improvement there, not to mention that the split is a style departure from the original implementation, I just didn't want to go through the nightmare of trying to fold path.sep into the regex. The null return when in error is meant to match the failure value I was getting pre-changes, and the param name change is meant to remove the collision with the path module.

And that is the end of My Issue, thanks!

**Comment by Allov** [comment]
Cool, can you make a pull request? I'll merge it.

**Comment by fcharest** [comment]
lol... commented with the wrong account. Can you make a pull request, I'll merge it...

**Comment by ddamico-cbc** [comment]
@fcharest For sure! Working on it right now but I don't have access to push a branch, can you help me out with that?

**Comment by fcharest** [comment]
yeah, you need to do a pull request. You have to fork this repo and do a pull request. Here's how: https://help.github.com/articles/using-pull-requests/

**Comment by ddamico-cbc** [comment]
Aha, now I see (I've never done this with a fork before). Thanks very much for the help!

**Comment by fcharest** [comment]
See merge in #6
